services:
  backend:
    build: ./backend
    container_name: canaltech-backend
    ports:
      - '3001:3001'
    volumes:
      - ./backend/prisma:/app/prisma
    restart: unless-stopped

  frontend:
    build: ./frontend
    container_name: canaltech-frontend
    ports:
      - '3000:3000'
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    depends_on:
      - backend
    restart: unless-stopped 