services:
  backend:
    build: ./backend
    container_name: canaltech-backend
    ports:
      - '3001:3001'
    environment:
      - NODE_ENV=production
    volumes:
       - ./backend:/app
    depends_on:
      - db
    restart: unless-stopped
  frontend:
    build: ./frontend
    container_name: canaltech-frontend
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    restart: unless-stopped
  db:
    image: alpine:latest
    container_name: canaltech-db
    volumes:
      - ./backend/prisma:/data
    command: sh -c "apk add --no-cache sqlite && tail -f /dev/null" 